// Code generated by "cmap-gen -package cmap -type string -map Map -shard Shard -new New -output cmap.go ."; DO NOT EDIT.

package cmap

import "hash/fnv"
import "sync"

// Map is sharded concurrent map which key type is string and
// value type is string
type Map struct {
	shards []*Shard
}

// New creates new Map with specified shards count
func New(nShards int) *Map {
	shards := make([]*Shard, nShards)
	for i := 0; i < nShards; i++ {
		shards[i] = NewShard()
	}
	return &Map{shards: shards}
}

func (c Map) hash(s string) uint32 {
	h := fnv.New32a()
	h.Write([]byte(s))
	return h.Sum32() % uint32(len(c.shards))
}

// Get returns the value stored by specified key
func (c Map) Get(key string) string {
	return c.shards[c.hash(key)].Get(key)
}

// Set stores the specified value under the specified key
func (c Map) Set(key string, value string) {
	c.shards[c.hash(key)].Set(key, value)
}

// Shard is concurrent map which key type is string and
// value type is string
type Shard struct {
	mu   sync.RWMutex
	data map[string]string
}

// NewShard creates new Shard
func NewShard() *Shard {
	return &Shard{
		data: make(map[string]string),
	}
}

// Get returns the value stored by specified key
func (c *Shard) Get(key string) string {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.data[key]
}

// Set stores the specified value under the specified key
func (c *Shard) Set(key string, value string) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.data[key] = value
}
